FROM nginx:latest

# RUN apk update && apk add bash

WORKDIR /etc/nginx

# Stream the nginx logs to stdout and stderr
# RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
#     ln -sf /dev/stderr /var/log/nginx/error.log

COPY nginx/ /etc/nginx
RUN mkdir /usr/public/www
COPY ui/ /usr/public/www

RUN nginx -t

EXPOSE 80

